### ISSUE TITLE
Docs (installation): Gemfile requires a pointer to repo

### ISSUE THREAD

**Issue by francisfuzz** [derekprior/dummy_locale#1]
## Summary

Hi, @derekprior ! Thanks for creating this gem. 😸 

In the README's installation, it says:

> Add gem "dummy_locale" to your Gemfile and bundle. 

However, adding it and running `bundle` to install it will result in the following error, since [it's not currently published to RubyGems.org](https://rubygems.org/search?query=dummy_locale):

```shell
$  touch Gemfile && echo "source https://rubygems.org\n\ngem \"dummy_locale\"" > Gemfile
$  bundle install
Fetching gem metadata from https://rubygems.org/.
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'dummy_locale' in any of the gem sources listed in your Gemfile.
```

As far as a next step, I suggest that either this gem gets published to RubyGems.org or the docs be updated to include this line:

> Add `gem "dummy_locale", :git => "https://github.com/derekprior/dummy_locale"` to your Gemfile and bundle.

**Comment by derekprior** [comment]
Good shout out. I forgot I never published it. The instructions are probably just a copy-paste from other gem scaffolding.

**Comment by derekprior** [comment]
I made some small changes to get the test suite passing on newer versions of Ruby and pushed up a release to RubyGems: https://rubygems.org/gems/dummy_locale

**Comment by francisfuzz** [comment]
🎉 , thank you!
